### PR TITLE
add strain to conversion

### PR DESCRIPTION
**Pull request by jmuransky**
Add unit for Strain

### CODE REVIEW

**Comment by marianban** [comment]
Does this work if you run npm run test?

**Comment by jmuransky** [comment]
Yes it does. Actually i had to run this command 2 hrs before as there was a
unit test failing somewhere (else). Now unit tests do run without any
problems...

Dňa ut 24. 7. 2018, 20:43 Marian Ban <notifications@github.com> napísal(a):

**Comment by marianban** [comment]
I ment the tests in this repo:)

**Comment by jmuransky** [comment]
I will check them tomorrow

Dňa ut 24. 7. 2018, 20:53 Marian Ban <notifications@github.com> napísal(a):

**Pull request merged**
